# Generated by Django 4.0 on 2022-05-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=250)),
                ('state_province', models.CharField(max_length=250)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('blood_type', models.CharField(blank=True, max_length=5)),
                ('skills', models.CharField(blank=True, max_length=250)),
                ('organization', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
