# Generated by Django 4.0 on 2022-05-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volah', '0002_alter_volunteer_blood_type_alter_volunteer_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='country',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
