# Generated by Django 4.0 on 2022-05-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volah', '0005_organization_alter_volunteer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='volah.organization'),
        ),
    ]
